version: '3'

services:
  db:
    image: mysql:8.0
    env_file: .env

    ports:
      - ${MYSQL_PORT}:3306
    container_name: ${PROJECT_NAME}-mysql
    volumes:
      - ./mysql/volumes:/var/lib/mysql
      - ./mysql/:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  go_app:
    env_file: .env

    build:
      dockerfile: ./Dockerfile 
      args:
        - APP_USERNAME=${APP_USERNAME}
        - APP_USER_PASSWORD=${APP_USER_PASSWORD}
        - LANG_VERSION=${LANG_VERSION}

    image: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}-golang

    ports:
      - ${APP_PORT}:8080
    volumes:
      - ./apps:/home/${APP_USERNAME}/apps
      - ./go/bin:/home/${APP_USERNAME}/go/bin
    tty: true

    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=db_dev
      - DB_USERNAME=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: /bin/bash
    depends_on:
      - db
    